language: node_js
sudo: false

node_js:
  - "5"
  - "6"
  - "7"

cache:
  directories:
    - "/home/travis/.yarn-cache"
    - bower_components

before_install:
  - "npm config set spin false"
  - "npm --version"
  - "phantomjs --version"

install:
  - "npm install -g yarn bower"
  - "yarn install --pure-lockfile --no-emoji"
  - "bower install"

script:
  - "npm test"

after_script:
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
  - "cat coverage/lcov.info | node_modules/codeclimate-test-reporter/bin/codeclimate.js"
