dist: trusty
language: node_js
sudo: false

node_js:
  - "6"
  - "8"

cache:
  directories:
    - "/home/travis/.yarn-cache"

before_install:
  - "yarn --version"

install:
  - "yarn install --pure-lockfile --no-emoji"

script:
  - "yarn flow"
  - "yarn test -- --coverage --verbose"

after_script:
  - "yarn run codecov"
