dist: trusty
language: node_js
sudo: false

node_js:
  - "6"
  - "8"

cache: yarn

matrix:
  include:
    - env: RUN_TESTS=1
    - env: RUN_FLOW=1

before_install:
  - "yarn --version"

install:
  - "yarn install --pure-lockfile --no-emoji"

script:
  - if [ -n "$RUN_FLOW" ]; then yarn flow; fi
  - if [ -n "$RUN_TESTS" ]; then yarn test -- --coverage --verbose; fi

after_script:
  - if [ -n "$RUN_TESTS" ]; then yarn codecov; fi
