language: node_js
sudo: false

node_js:
  - "6"
  - "7"

cache:
  directories:
    - "/home/travis/.yarn-cache"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "yarn --version"
  - "phantomjs --version"
  - "git clone https://github.com/ontohub/ontohub-backend ../ontohub-backend"
  - "ln -s $(readlink -f ../ontohub-backend/spec/support/api/schemas) app/schemas"
  - "ls -la app/schemas"

install:
  - "yarn install --pure-lockfile --no-emoji"
  - "yarn run bower install"

script:
  - "yarn test"

after_script:
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
  - "cat coverage/lcov.info | node_modules/codeclimate-test-reporter/bin/codeclimate.js"
